site_name: "File Monitoring System"
site_url: "https://juanradam.github.io/FileMonitoringSystem/"

# MkDocs leerá los .md desde docs/ y generará el HTML en site/
docs_dir: docs
site_dir: site

# Usamos URL con .html porque estamos en un subdirectorio de GitHub Pages
use_directory_urls: false

theme:
  name: material

markdown_extensions:
  - toc:
      permalink: true
  - admonition

nav:
  - Home: SUMMARY.md

  - Introducción: 01-introduccion.md
  - Especificación de Requisitos: 02-requisitos.md

  - Diseño (Diagramas):
      - Casos de uso: 03-diseno.md#3-1-casos-de-uso
      - Diagrama entidad-relación: 03-diseno.md#3-2-diagrama-entidad-relación
      - Esquema para BD no relacional: 03-diseno.md#3-3-esquema-para-bd-no-relacional
      - Diagrama de clases del modelo: 03-diseno.md#3-4-diagrama-de-clases-del-modelo
      - Diagramas de secuencia: 03-diseno.md#3-5-diagramas-de-secuencia

  - Implementación (GIT): 04-implementacion.md
  - Resultado (Manual de usuario): 05-resultado.md
  - Conclusiones: 06-conclusiones.md
