site_name: "File Monitoring System"
site_url: "https://juanradam.github.io/FileMonitoringSystem/"

docs_dir: docs
site_dir: site
use_directory_urls: false

theme:
  name: mkdocs          # puedes usar 'mkdocs' o 'github' si lo tienes instalado

plugins:
  - search
  - mermaid2            # si sigues queriendo Mermaid

markdown_extensions:
  #1) mdx_truly_sane_lists para listas profundizadas sin líos
  - mdx_truly_sane_lists:
      nested_indent: 2   # número de espacios para cada nivel (igual que GFM)
      truly_sane: true

  #2) el resto de tus extensiones habituales
  - toc:
      permalink: true
  - admonition
  - fenced_code
  - codehilite:
      guess_lang: false
