site_name: "File Monitoring System"
site_url: "https://juanradam.github.io/FileMonitoringSystem/"

# MkDocs leerá los .md desde docs/ y generará el HTML en site/
docs_dir: docs
site_dir: site

# Usamos URL con .html porque estamos en un subdirectorio de GitHub Pages
use_directory_urls: false

theme:
  name: readthedocs

plugins:
  - search
  - mermaid2


markdown_extensions:
  # este orden importa: super­fences arriba, después highlight
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_code_format
  - pymdownx.highlight        # resaltado de código con Highlight.js
  - toc:
      permalink: true
  - admonition

nav:
  - Home: index.md
  - Introducción: 01-introduccion.md
  - Especificación de Requisitos: 02-requisitos.md
  - Diseño (Diagramas): 03-diseno.md
  - Implementación (GIT): 04-implementacion.md
  - Resultado (Manual de usuario): 05-resultado.md
  - Conclusiones: 06-conclusiones.md
