site_name: "File Monitoring System"
site_url: "https://juanradam.github.io/FileMonitoringSystem/"

docs_dir: docs
site_dir: site
use_directory_urls: false

theme:
  name: github
  highlightjs: true
  hljs_style: github

plugins:
  - search
  - mermaid2

markdown_extensions:
  - mdx_truly_sane_lists
  - toc:
      permalink: true
  - admonition
  - fenced_code
  - codehilite:
      guess_lang: false

nav:
  - Home: index.md
  - Introducci칩n: 01-introduccion.md
  - Especificaci칩n de Requisitos: 02-requisitos.md
  - Dise침o (Diagramas): 03-diseno.md
  - Implementaci칩n (GIT): 04-implementacion.md
  - Resultado (Manual de usuario): 05-resultado.md
  - Conclusiones: 06-conclusiones.md
