site_name: "File Monitoring System"

# Esta URL es la de tu GitHub Pages:
# (reemplaza <tu-usuario> y <tu-repo> con tus valores)
site_url: "https://juanradam.github.io/FileMonitoringSystem/"

# Carpeta donde MkDocs busca los .md
docs_dir: docs

# Carpeta donde MkDocs genera el HTML
site_dir: site

# Para que los enlaces se construyan bien bajo el subdirectorio
use_directory_urls: false

theme:
  name: material
  palette:
    primary: 'indigo'
    accent: 'indigo'
  font:
    text: 'Roboto'
    code: 'Roboto Mono'
  favicon: 'img/diagrama_casos_de_uso.png'  # solo a modo de ejemplo
  # (Puedes personalizar más opciones de Material aquí)

markdown_extensions:
  - toc:
      permalink: true
  - admonition

nav:
  - Introducción: 01-introduccion.md
  - Especificación de Requisitos: 02-requisitos.md
  - Diseño (Diagramas):
      - Casos de uso: 03-diseno.md#31-casos-de-uso
      - Diagrama entidad-relación: 03-diseno.md#32-diagrama-entidad-relación
      - Esquema para BD no relacional: 03-diseno.md#33-esquema-para-bd-no-relacional
      - Diagrama de clases del modelo: 03-diseno.md#34-diagrama-de-clases-del-modelo
      - Diagramas de secuencia: 03-diseno.md#35-diagramas-de-secuencia
  - Implementación (GIT): 04-implementacion.md
  - Resultado (Manual de usuario): 05-resultado.md
  - Conclusiones: 06-conclusiones.md
