site_name: "File Monitoring System"
site_url: "https://juanradam.github.io/FileMonitoringSystem/"

docs_dir: docs
site_dir: site
use_directory_urls: false

theme:
  name: readthedocs     # ← tema Read the Docs, muy estable con código

markdown_extensions:
  - toc:
      permalink: true   # añade enlaces “§” junto a cada título
  - admonition         # para bloques tipo nota/advertencia
  - fenced_code        # fuerza triple-backticks para todo bloque de código
  - codehilite:
      guess_lang: false # resaltado sin “adivinar” el lenguaje

nav:
  - Home: index.md
  - Introducción: 01-introduccion.md
  - Especificación de Requisitos: 02-requisitos.md
  - Diseño (Diagramas): 03-diseno.md
  - Implementación (GIT): 04-implementacion.md
  - Resultado (Manual de usuario): 05-resultado.md
  - Conclusiones: 06-conclusiones.md
