# mkdocs.yml
site_name: "File Monitoring System"
site_url: "https://juanradam.github.io/FileMonitoringSystem/"

docs_dir: docs
site_dir: site
use_directory_urls: false

theme:
  name: readthedocs

plugins:
  - search
  - mermaid2                     # inyecta Mermaid.js en el HTML :contentReference[oaicite:0]{index=0}

markdown_extensions:
  - toc:
      permalink: true
  - admonition
  - pymdownx.superfences:        # gestiona todos los bloques fenced y preserva indentación
      disable_indented_code_blocks: true  # evita que 4 espacios se consideren código :contentReference[oaicite:1]{index=1}
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:mermaid2.fence_mermaid  # deja pasar los bloques mermaid al plugin :contentReference[oaicite:2]{index=2}
  - pymdownx.highlight           # resalta sin reindentar

nav:
  - Home: index.md
  - Introducción: 01-introduccion.md
  - Especificación de Requisitos: 02-requisitos.md
  - Diseño (Diagramas): 03-diseno.md
  - Implementación (GIT): 04-implementacion.md
  - Resultado (Manual de usuario): 05-resultado.md
  - Conclusiones: 06-conclusiones.md
