site_name: "File Monitoring System"
site_url: "https://juanradam.github.io/FileMonitoringSystem/"

docs_dir: docs
site_dir: site
use_directory_urls: false

theme:
  name: github                # ← tema GitHub de MkDocs
  highlightjs: true           # ← usa Highlight.js como GitHub
  hljs_style: github          # ← paleta de resaltado “GitHub”

plugins:
  - search
  - mermaid2                  # ← inyecta Mermaid.js y renderiza tus ```mermaid``` :contentReference[oaicite:1]{index=1}

markdown_extensions:
  - toc:
      permalink: true
  - admonition
  - fenced_code               # ← asegura que sólo triple backticks creen bloques de código
  - codehilite:
      guess_lang: false       # ← no “adivina” el lenguaje

nav:
  - Home: index.md
  - Introducción: 01-introduccion.md
  - Especificación de Requisitos: 02-requisitos.md
  - Diseño (Diagramas): 03-diseno.md
  - Implementación (GIT): 04-implementacion.md
  - Resultado (Manual de usuario): 05-resultado.md
  - Conclusiones: 06-conclusiones.md
