name: Build and Deploy MkDocs to GitHub Pages

permissions:
  contents: write
  pages: write
  id-token: write

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  deploy:
    name: Deploy MkDocs site
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install \
            mkdocs \                  # core de MkDocs
            mkdocs-github \           # tema “GitHub” de MkDocs
            mkdocs-mermaid2-plugin \  # renderiza bloques ```mermaid```
            mdx-truly-sane-lists \    # listas anidadas con indentado GFM
            pymdown-extensions        # superfences, highlight, etc.

      - name: Build MkDocs site
        run: mkdocs build --clean

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./site
